# Python CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2

apt-run: &apt-install
  name: Install apt packages
  command: |
    sudo apt-get update
    sudo apt-get install build-essential pandoc

pip-run: &pip-install
  name: Install Python dependencies
  command: |
    python3 -m venv venv
    . venv/bin/activate
    pip install -r pip-requirements.txt
    pip install sphinx pytest
    pip install sphinx-astropy sphinx-bootstrap-theme
    pip install git+https://github.com/jupyter/nbconvert

jobs:

  build:
    docker:
      - image: circleci/python:3.7

    branches:
      ignore:
        - gh-pages
        - rst

    steps:
      - checkout
      - add_ssh_keys: # add GitHub SSH keys
          fingerprints:
            - 32:53:df:4a:53:71:25:8b:73:42:71:c8:57:8a:3f:f7
      - run: *apt-install # run the apt install defined above
      - run: *pip-install # run the pip install defined above

      - restore_cache:
          keys:
            - astropy-cache

      - run:
          name: Build documentation
          command: |
            . venv/bin/activate
            make html

      - save_cache:
          key: astropy-cache
          paths:
            - ~/.astropy/cache/

      - store_artifacts:
          path: build/html

      - run:
          name: Built documentation is available at
          command: |
            DOCS_URL="${CIRCLE_BUILD_URL}/artifacts/${CIRCLE_NODE_INDEX}/${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}/build/html/index.html"; echo $DOCS_URL

      - run:
          name: Push to gh-pages branch
          command: |
            bash .circleci/gh-pages-push.sh


notify:
  webhooks:
    - url: https://giles.cadair.com/circleci
