# Python CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2

apt-run: &apt-install
  name: Install apt packages
  command: |
    sudo apt-get update
    sudo apt-get install build-essential pandoc

pip-run: &pip-install
  name: Install Python dependencies
  command: |
    python3 -m venv venv
    . venv/bin/activate
    pip install -r pip-requirements.txt
    pip install astropy_helpers sphinx pytest
    pip install git+https://github.com/jupyter/nbconvert

jobs:

  build:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout
      - add_ssh_keys: # add GitHub SSH keys
          fingerprints:
            - 32:53:df:4a:53:71:25:8b:73:42:71:c8:57:8a:3f:f7
      - run: *apt-install # run the apt install defined above
      - run: *pip-install # run the pip install defined above

      # - restore_cache: # Need cache for all tutorial data!
      #     keys: sample-data-v1

      - run:
          name: Build documentation
          command: |
            . venv/bin/activate
            make html

      - store_artifacts:
          path: build/html

      - run:
          name: Built documentation is available at
          command: |
            DOCS_URL="${CIRCLE_BUILD_URL}/artifacts/${CIRCLE_NODE_INDEX}/${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}/build/html/index.html"; echo $DOCS_URL

      - run:
          name: Push to RTD branch
          command: |
            bash .circleci/rtd-push.sh

      # - save_cache: # Specify what paths to cache
      #     key: sample-data-v1
      #     paths:
      #       - ~/sunpy/data/sample_data

notify:
  webhooks:
    - url: https://giles.cadair.com/circleci
