title:
author:
logo: logo.svg
execute:
  execute_notebooks: force
repository:
  url: 
  branch: main/
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  analytics:
    google_analytics_id: "G-ZBXC3EFGGJ"
launch_buttons: 
  notebook_interface: jupyterlab
  thebe: true
sphinx:
  config:
    html_show_copyright: false
